package com.applicationregisteration.fx.byezbercime.util;

public enum CountryPhoneCode {
    // A - B
    AFGHANISTAN("AF", "+93", "Afganistan"),
    GERMANY("DE", "+49", "Almanya"),
    ANGUILLA("AI", "+1264", "Anguilla"),
    ANTIGUA_AND_BARBUDA("AG", "+1268", "Antigua ve Barbuda"),
    ARGENTINA("AR", "+54", "Arjantin"),
    ALBANIA("AL", "+355", "Arnavutluk"),
    ARUBA("AW", "+297", "Aruba"),
    ASCENSION_ISLAND("AC", "+247", "Ascension Adası"),
    AUSTRALIA("AU", "+61", "Avustralya"),
    AUSTRIA("AT", "+43", "Avusturya"),
    AZERBAIJAN("AZ", "+994", "Azerbaycan"),
    BAHAMAS("BS", "+1242", "Bahamalar"),
    BAHRAIN("BH", "+973", "Bahreyn"),
    BANGLADESH("BD", "+880", "Bangladeş"),
    BARBADOS("BB", "+1246", "Barbados"),
    BELGIUM("BE", "+32", "Belçika"),
    BELIZE("BZ", "+501", "Belize"),
    BENIN("BJ", "+229", "Benin"),
    BERMUDA("BM", "+1441", "Bermuda"),
    BELARUS("BY", "+375", "Beyaz Rusya / Belarus"),
    BHUTAN("BT", "+975", "Butan"),
    BOLIVIA("BO", "+591", "Bolivya"),
    BOSNIA_HERZEGOVINA("BA", "+387", "Bosna Hersek"),
    BOTSWANA("BW", "+267", "Botsvana"),
    BRAZIL("BR", "+55", "Brezilya"),
    BRITISH_VIRGIN_ISLANDS("VG", "+1284", "Britanya Virjin Adaları"),
    BRUNEI("BN", "+673", "Brunei"),
    BULGARIA("BG", "+359", "Bulgaristan"),
    BURKINA_FASO("BF", "+226", "Burkina Faso"),
    BURUNDI("BI", "+257", "Burundi"),

    // C - Ç - D - E
    CHAD("TD", "+235", "Çad"),
    CAYMAN_ISLANDS("KY", "+1345", "Cayman Adaları"),
    CZECH_REPUBLIC("CZ", "+420", "Çek Cumhuriyeti"),
    ALGERIA("DZ", "+213", "Cezayir"),
    DJIBOUTI("DJ", "+253", "Cibuti"),
    CHINA("CN", "+86", "Çin"),
    COOK_ISLANDS("CK", "+682", "Cook Adaları"),
    COLOMBIA("CO", "+57", "Kolombiya"),
    COMOROS("KM", "+269", "Komorlar"),
    CONGO_REPUBLIC("CG", "+242", "Kongo Cumhuriyeti"),
    DR_CONGO("CD", "+243", "Kongo Demokratik Cumhuriyeti"),
    NORTH_KOREA("KP", "+1016", "Kore, Kuzey"),
    SOUTH_KOREA("KR", "+82", "Kore, Güney"),
    COSTA_RICA("CR", "+506", "Kosta Rika"),
    IVORY_COAST("CI", "+225", "Fildişi Sahili"),
    CROATIA("HR", "+385", "Hırvatistan"),
    CUBA("CU", "+53", "Küba"),
    CURACAO("CW", "+1758", "Curaçao"),
    CYPRUS("CY", "+357", "Kıbrıs"),
    DENMARK("DK", "+45", "Danimarka"),
    DIEGO_GARCIA("DG", "+246", "Diego Garcia"),
    DOMINICA("DM", "+1767", "Dominika"),
    DOMINICAN_REPUBLIC_1("DO", "+1809", "Dominik Cumhuriyeti"),
    DOMINICAN_REPUBLIC_2("DO", "+1829", "Dominik Cumhuriyeti"),
    DOMINICAN_REPUBLIC_3("DO", "+1849", "Dominik Cumhuriyeti"),
    ECUADOR("EC", "+593", "Ekvador"),
    EQUATORIAL_GUINEA("GQ", "+240", "Ekvator Ginesi"),
    EL_SALVADOR("SV", "+503", "El Salvador"),
    ARMENIA("AM", "+374", "Ermenistan"),
    ERITREA("ER", "+291", "Eritre"),
    ESTONIA("EE", "+372", "Estonya"),
    ETHIOPIA("ET", "+251", "Etiyopya"),

    // F - G - H
    FALKLAND_ISLANDS("FK", "+1670", "Falkland Adaları"),
    FAROE_ISLANDS("FO", "+298", "Faroe Adaları"),
    MOROCCO_ALT("MA", "+1684", "Fas (Alternatif)"),
    FIJI("FJ", "+679", "Fiji"),
    PHILIPPINES("PH", "+63", "Filipinler"),
    PALESTINE("PS", "+970", "Filistin"),
    FINLAND("FI", "+358", "Finlandiya"),
    FRANCE("FR", "+33", "Fransa"),
    FRENCH_GUIANA("GF", "+594", "Fransız Guyanası"),
    FRENCH_POLYNESIA("PF", "+689", "Fransız Polinezyası"),
    GABON("GA", "+241", "Gabon"),
    GAMBIA("GM", "+220", "Gambia"),
    GEORGIA("GE", "+995", "Gürcistan"),
    GHANA("GH", "+233", "Gana"),
    GIBRALTAR("GI", "+350", "Cebelitarık"),
    GREECE("GR", "+30", "Yunanistan"),
    GREENLAND("GL", "+299", "Grönland"),
    GRENADA("GD", "+1473", "Grenada"),
    GUADELOUPE("GP", "+590", "Guadeloupe"),
    GUAM("GU", "+1671", "Guam"),
    GUATEMALA("GT", "+502", "Guatemala"),
    GUINEA("GN", "+224", "Gine"),
    GUINEA_BISSAU("GW", "+245", "Gine-Bissau"),
    GUYANA("GY", "+592", "Guyana"),
    HAITI("HT", "+509", "Haiti"),
    HONDURAS("HN", "+504", "Honduras"),
    HONG_KONG("HK", "+852", "Hong Kong"),
    HUNGARY("HU", "+36", "Macaristan"),

    // I - İ - J - K
    ICELAND("IS", "+354", "İzlanda"),
    INDIA("IN", "+91", "Hindistan"),
    INDONESIA("ID", "+62", "Endonezya"),
    IRAN("IR", "+98", "İran"),
    IRAQ("IQ", "+964", "Irak"),
    IRELAND("IE", "+353", "İrlanda"),
    ISRAEL("IL", "+972", "İsrail"),
    ITALY("IT", "+39", "İtalya"),
    JAMAICA_1("JM", "+1876", "Jamaika"),
    JAMAICA_2("JM", "+1658", "Jamaika (Alternatif)"),
    JAPAN("JP", "+81", "Japonya"),
    JORDAN("JO", "+962", "Ürdün"),
    KAZAKHSTAN("KZ", "+7", "Kazakistan"),
    KENYA("KE", "+254", "Kenya"),
    KIRIBATI("KI", "+686", "Kiribati"),
    KUWAIT("KW", "+965", "Kuveyt"),
    KYRGYZSTAN("KG", "+996", "Kırgızistan"),

    // L - M - N
    LAOS("LA", "+856", "Laos"),
    LATVIA("LV", "+371", "Letonya"),
    LEBANON("LB", "+961", "Lübnan"),
    LESOTHO("LS", "+266", "Lesotho"),
    LIBERIA("LR", "+231", "Liberya"),
    LIBYA("LY", "+218", "Libya"),
    LIECHTENSTEIN("LI", "+423", "Liechtenstein"),
    LITHUANIA("LT", "+370", "Litvanya"),
    LUXEMBOURG("LU", "+352", "Lüksemburg"),
    MACAU("MO", "+853", "Makao"),
    NORTH_MACEDONIA("MK", "+389", "Kuzey Makedonya"),
    MADAGASCAR("MG", "+261", "Madagaskar"),
    MALAWI("MW", "+265", "Malavi"),
    MALAYSIA("MY", "+60", "Malezya"),
    MALDIVES("MV", "+960", "Maldivler"),
    MALI("ML", "+223", "Mali"),
    MALTA("MT", "+356", "Malta"),
    MARSHALL_ISLANDS("MH", "+692", "Marshall Adaları"),
    MARTINIQUE("MQ", "+596", "Martinik"),
    MAURITANIA("MR", "+222", "Moritanya"),
    MAURITIUS("MU", "+230", "Mauritius"),
    MAYOTTE("YT", "+262", "Mayotte"),
    MEXICO("MX", "+52", "Meksika"),
    MICRONESIA("FM", "+691", "Mikronezya"),
    MOLDOVA("MD", "+373", "Moldova"),
    MONACO("MC", "+377", "Monako"),
    MONGOLIA("MN", "+976", "Moğolistan"),
    MONTENEGRO("ME", "+382", "Karadağ"),
    MONTSERRAT("MS", "+1664", "Montserrat"),
    MOROCCO("MA", "+212", "Fas"),
    MOZAMBIQUE("MZ", "+258", "Mozambik"),
    MYANMAR("MM", "+95", "Myanmar"),
    NAMIBIA("NA", "+264", "Namibya"),
    NAURU("NR", "+674", "Nauru"),
    NEPAL("NP", "+977", "Nepal"),
    NETHERLANDS("NL", "+31", "Hollanda"),
    NEW_CALEDONIA("NC", "+687", "Yeni Kaledonya"),
    NEW_ZEALAND("NZ", "+64", "Yeni Zelanda"),
    NICARAGUA("NI", "+505", "Nikaragua"),
    NIGER("NE", "+227", "Nijer"),
    NIGERIA("NG", "+234", "Nijerya"),
    NIUE("NU", "+683", "Niue"),
    NORWAY("NO", "+47", "Norveç"),

    // O - Ö - P - R
    OMAN("OM", "+968", "Umman"),
    PAKISTAN("PK", "+92", "Pakistan"),
    PALAU("PW", "+680", "Palau"),
    PANAMA("PA", "+507", "Panama"),
    PAPUA_NEW_GUINEA("PG", "+675", "Papua Yeni Gine"),
    PARAGUAY("PY", "+595", "Paraguay"),
    PERU("PE", "+51", "Peru"),
    POLAND("PL", "+48", "Polonya"),
    PORTUGAL("PT", "+351", "Portekiz"),
    PUERTO_RICO_1("PR", "+1787", "Porto Riko"),
    PUERTO_RICO_2("PR", "+1939", "Porto Riko (Alternatif)"),
    QATAR("QA", "+974", "Katar"),
    REUNION("RE", "+262", "Reunion"),
    ROMANIA("RO", "+40", "Romanya"),
    RUSSIA("RU", "+7", "Rusya"),
    RWANDA("RW", "+250", "Ruanda"),

    // S - Ş
    SAINT_KITTS_AND_NEVIS("KN", "+1869", "Saint Kitts ve Nevis"),
    SAINT_LUCIA("LC", "+1758", "Saint Lucia"),
    SAINT_MARTIN("MF", "+1599", "Saint Martin"),
    SAINT_VINCENT("VC", "+1784", "Saint Vincent ve Grenadinler"),
    SAMOA("WS", "+685", "Samoa"),
    SAN_MARINO("SM", "+378", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "+239", "Sao Tome ve Principe"),
    SAUDI_ARABIA("SA", "+966", "Suudi Arabistan"),
    SENEGAL("SN", "+221", "Senegal"),
    SERBIA("RS", "+381", "Sırbistan"),
    SEYCHELLES("SC", "+248", "Seyşeller"),
    SIERRA_LEONE("SL", "+232", "Sierra Leone"),
    SINGAPORE("SG", "+65", "Singapur"),
    SINT_MAARTEN("SX", "+1721", "Sint Maarten"),
    SLOVAKIA("SK", "+421", "Slovakya"),
    SLOVENIA("SI", "+386", "Slovenya"),
    SOLOMON_ISLANDS("SB", "+677", "Solomon Adaları"),
    SOMALIA("SO", "+252", "Somali"),
    SOUTH_AFRICA("ZA", "+27", "Güney Afrika"),
    SOUTH_SUDAN("SS", "+211", "Güney Sudan"),
    SPAIN("ES", "+34", "İspanya"),
    SRI_LANKA("LK", "+94", "Sri Lanka"),
    SUDAN("SD", "+249", "Sudan"),
    SURINAME("SR", "+597", "Surinam"),
    ESVATINI("SZ", "+268", "Esvatini / Svaziland"),
    SWEDEN("SE", "+46", "İsveç"),
    SWITZERLAND("CH", "+41", "İsviçre"),
    SYRIA("SY", "+963", "Suriye"),

    // T - U - Ü - V - Y - Z
    TAIWAN("TW", "+886", "Tayvan"),
    TAJIKISTAN("TJ", "+992", "Tacikistan"),
    TANZANIA("TZ", "+255", "Tanzanya"),
    THAILAND("TH", "+66", "Tayland"),
    TOGO("TG", "+228", "Togo"),
    TOKELAU("TK", "+690", "Tokelau"),
    TONGA("TO", "+676", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "+1868", "Trinidad ve Tobago"),
    TUNISIA("TN", "+216", "Tunus"),
    TURKEY("TR", "+90", "Türkiye"),
    TURKMENISTAN("TM", "+993", "Türkmenistan"),
    TURKS_AND_CAICOS("TC", "+1649", "Turks ve Caicos Adaları"),
    TUVALU("TV", "+688", "Tuvalu"),
    UGANDA("UG", "+256", "Uganda"),
    UKRAINE("UA", "+380", "Ukrayna"),
    UAE("AE", "+971", "Birleşik Arap Emirlikleri"),
    UNITED_KINGDOM("GB", "+44", "İngiltere / Birleşik Krallık"),
    USA_CANADA("US", "+1", "Amerika Birleşik Devletleri / Kanada"),
    URUGUAY("UY", "+598", "Uruguay"),
    UZBEKISTAN("UZ", "+998", "Özbekistan"),
    VANUATU("VU", "+678", "Vanuatu"),
    VATICAN("VA", "+3906698", "Vatikan"),
    VENEZUELA("VE", "+58", "Venezuela"),
    VIETNAM("VN", "+84", "Vietnam"),
    US_VIRGIN_ISLANDS("VI", "+1340", "Amerikan Virjin Adaları"),
    WALLIS_AND_FUTUNA("WF", "+681", "Wallis ve Futuna"),
    YEMEN("YE", "+967", "Yemen"),
    ZAMBIA("ZM", "+260", "Zambiya"),
    ZIMBABWE("ZW", "+263", "Zimbabve");

    private final String isoCode;
    private final String phoneCode;
    private final String countryName;

    CountryPhoneCode(String isoCode, String phoneCode, String countryName) {
        this.isoCode = isoCode;
        this.phoneCode = phoneCode;
        this.countryName = countryName;
    }

    public String getIsoCode() { return isoCode; }
    public String getPhoneCode() { return phoneCode; }
    public String getCountryName() { return countryName; }

    // Kod ile Enum bulmak için yardımcı metot (Örn: "+90" verilince TURKEY döner)
    public static CountryPhoneCode getByPhoneCode(String code) {
        for (CountryPhoneCode c : values()) {
            if (c.getPhoneCode().equals(code)) {
                return c;
            }
        }
        return null;
    }
}
